# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: ./cmd/rwp/
    env:
      - CGO_ENABLED=0
    id: rwp
    binary: rwp
    goos:
      - linux
      - windows
      - darwin
    goamd64:
      - v3

#  - main: ./cmd/server/
#    env:
#      - CGO_ENABLED=0
#    id: rwp-server
#    binary: rwp-server
#    goos:
#      - linux
#      - windows
#      - darwin

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    # Used to start with {{ .ProjectName }}
    name_template: >-
      rwp_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
