// Code generated by "stringer -type Scheme"; DO NOT EDIT.

package protection

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoDRM-0]
	_ = x[Generic-1]
	_ = x[LCP-2]
	_ = x[Adept-3]
	_ = x[BarnesAndNoble-4]
	_ = x[Fairplay-5]
	_ = x[Kobo-6]
}

const _Scheme_name = "NoDRMGenericLCPAdeptBarnesAndNobleFairplayKobo"

var _Scheme_index = [...]uint8{0, 5, 12, 15, 20, 34, 42, 46}

func (i Scheme) String() string {
	if i < 0 || i >= Scheme(len(_Scheme_index)-1) {
		return "Scheme(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Scheme_name[_Scheme_index[i]:_Scheme_index[i+1]]
}
